server:
  port: 8084
spring:
  data:
    mongodb:
      database: accounts
      host: localhost
      port: 27017
info:
  app:
    name: Spring Boot Actuator Demo
    web: *
  hello: Hi there!!!
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, restart, env
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
logging:
  level:
    root: info