server:
  port: 8085
spring:
  data:
    mongodb:
      database: credits
      host: localhost
      port: 27017

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, restart, env
    shutdown:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true
logging:
  level:
    root: info